"""add_fulltext_search_tsv_columns

Revision ID: 8888da0ec72d
Revises: 600a05159956
Create Date: 2026-02-16 12:58:14.575247
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic
revision: str = '8888da0ec72d'
down_revision: Union[str, None] = '600a05159956'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('embeddings', sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', COALESCE(content, ''))", persisted=True), nullable=True))
    op.create_index('ix_embeddings_search_tsv', 'embeddings', ['search_tsv'], unique=False, postgresql_using='gin')
    op.add_column('messages', sa.Column('search_tsv', postgresql.TSVECTOR(), sa.Computed("to_tsvector('simple', COALESCE(transcribed_text, ''))", persisted=True), nullable=True))
    op.create_index('ix_messages_search_tsv', 'messages', ['search_tsv'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_messages_search_tsv', table_name='messages', postgresql_using='gin')
    op.drop_column('messages', 'search_tsv')
    op.drop_index('ix_embeddings_search_tsv', table_name='embeddings', postgresql_using='gin')
    op.drop_column('embeddings', 'search_tsv')
    # ### end Alembic commands ###
