"""enhance_budget_item_model

Revision ID: 600a05159956
Revises: 0c7ea7475948
Create Date: 2026-02-12 10:35:56.938754
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic
revision: str = '600a05159956'
down_revision: Union[str, None] = '0c7ea7475948'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('budget_items', sa.Column('stage_id', sa.BigInteger(), nullable=True))
    op.add_column('budget_items', sa.Column('description', sa.Text(), nullable=True))
    op.add_column('budget_items', sa.Column('is_confirmed', sa.Boolean(), nullable=False))
    op.add_column('budget_items', sa.Column('confirmed_by_user_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_budget_items_stage_id'), 'budget_items', ['stage_id'], unique=False)
    op.create_foreign_key(None, 'budget_items', 'users', ['confirmed_by_user_id'], ['id'])
    op.create_foreign_key(None, 'budget_items', 'stages', ['stage_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'budget_items', type_='foreignkey')
    op.drop_constraint(None, 'budget_items', type_='foreignkey')
    op.drop_index(op.f('ix_budget_items_stage_id'), table_name='budget_items')
    op.drop_column('budget_items', 'confirmed_by_user_id')
    op.drop_column('budget_items', 'is_confirmed')
    op.drop_column('budget_items', 'description')
    op.drop_column('budget_items', 'stage_id')
    # ### end Alembic commands ###
