"""add_tenants_table_and_tenant_id

Revision ID: c7d4150f85cf
Revises: 8888da0ec72d
Create Date: 2026-02-17 16:21:31.855914
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic
revision: str = 'c7d4150f85cf'
down_revision: Union[str, None] = '8888da0ec72d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('telegram_bot_token', sa.String(length=100), nullable=False),
    sa.Column('telegram_bot_username', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_telegram_bot_token'), 'tenants', ['telegram_bot_token'], unique=True)
    op.add_column('embeddings', sa.Column('tenant_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_embeddings_tenant_id'), 'embeddings', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'embeddings', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('tenant_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_messages_tenant_id'), 'messages', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')
    op.add_column('projects', sa.Column('tenant_id', sa.BigInteger(), nullable=True))
    op.create_index(op.f('ix_projects_tenant_id'), 'projects', ['tenant_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'tenants', ['tenant_id'], ['id'], ondelete='CASCADE')

    # ── Data migration: create a default tenant from TELEGRAM_BOT_TOKEN ──
    # Insert default tenant; backfill existing rows so they belong to it.
    import os
    token = os.environ.get("TELEGRAM_BOT_TOKEN", "")
    if token:
        conn = op.get_bind()
        result = conn.execute(
            sa.text(
                "INSERT INTO tenants (name, telegram_bot_token, is_active) "
                "VALUES (:name, :token, true) RETURNING id"
            ),
            {"name": "Default Bot", "token": token},
        )
        tenant_id = result.scalar()
        if tenant_id:
            for table in ("projects", "messages", "embeddings"):
                conn.execute(
                    sa.text(f"UPDATE {table} SET tenant_id = :tid WHERE tenant_id IS NULL"),
                    {"tid": tenant_id},
                )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_tenant_id'), table_name='projects')
    op.drop_column('projects', 'tenant_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_tenant_id'), table_name='messages')
    op.drop_column('messages', 'tenant_id')
    op.drop_constraint(None, 'embeddings', type_='foreignkey')
    op.drop_index(op.f('ix_embeddings_tenant_id'), table_name='embeddings')
    op.drop_column('embeddings', 'tenant_id')
    op.drop_index(op.f('ix_tenants_telegram_bot_token'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
