"""Add responsible_contact to stages and sub_stages

Revision ID: 0c7ea7475948
Revises: b681d11e3c55
Create Date: 2026-02-11 18:51:55.501165
"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic
revision: str = '0c7ea7475948'
down_revision: Union[str, None] = 'b681d11e3c55'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stages', sa.Column('responsible_contact', sa.String(length=255), nullable=True))
    op.add_column('sub_stages', sa.Column('responsible_contact', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sub_stages', 'responsible_contact')
    op.drop_column('stages', 'responsible_contact')
    # ### end Alembic commands ###
